version: "2"

networks:
  itoe-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.110.0/24
          gateway: 172.20.110.1
          
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    networks:
      itoe-network:
        ipv4_address: 172.20.110.100
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    #volumes:
      #- zookeeper_data:/bitnami/zookeeper
  kafka-0:
    image: docker.io/bitnami/kafka:3.2
    networks:
      itoe-network:
        ipv4_address: 172.20.110.101
    ports:
      #- 19092:9092
      - 9093:9093
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=0
      #- KAFKA_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
      #- KAFKA_LISTENERS=PLAINTEXT://127.0.0.1:9092
      #- KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:19092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://172.20.110.101:9092,EXTERNAL://localhost:9093
    depends_on:
      - zookeeper
  kafka-1:
    image: docker.io/bitnami/kafka:3.2
    networks:
      itoe-network:
        ipv4_address: 172.20.110.102
    ports:
      #- 19092:9092
      - 19093:9093
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=1
      #- KAFKA_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
      #- KAFKA_LISTENERS=PLAINTEXT://127.0.0.1:9092
      #- KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:29092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://172.20.110.102:9092,EXTERNAL://localhost:19093
    depends_on:
      - zookeeper
  kafka-2:
    image: docker.io/bitnami/kafka:3.2
    networks:
      itoe-network:
        ipv4_address: 172.20.110.103
    ports:
      #- 19092:9092
      - 29093:9093
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=2
      #- KAFKA_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
      #- KAFKA_LISTENERS=PLAINTEXT://127.0.0.1:9092
      #- KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:39092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://172.20.110.103:9092,EXTERNAL://localhost:29093
    depends_on:
      - zookeeper
  kafka-3:
    image: docker.io/bitnami/kafka:3.2
    networks:
      itoe-network:
        ipv4_address: 172.20.110.104
    ports:
      #- 19092:9092
      - 39093:9093
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=3
      #- KAFKA_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
      #- KAFKA_LISTENERS=plaintext://127.0.0.1:9092
      #- KAFKA_ADVERTISED_LISTENERS=plaintext://127.0.0.1:49092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://172.20.110.104:9092,EXTERNAL://localhost:39093
    depends_on:
      - zookeeper
  kafka-4:
    image: docker.io/bitnami/kafka:3.2
    networks:
      itoe-network:
        ipv4_address: 172.20.110.105
    ports:
      #- 19092:9092
      - 49093:9093
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=4
      #- KAFKA_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
      #- KAFKA_LISTENERS=PLAINTEXT://127.0.0.1:9092
      #- KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:59092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://172.20.110.105:9092,EXTERNAL://localhost:49093
    depends_on:
      - zookeeper
  kafdrop:
    image: obsidiandynamics/kafdrop
    networks:
      itoe-network:
        ipv4_address: 172.20.110.200
    ports:
      - 9000:9000
    environment:
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
      - KAFKA_BROKERCONNECT=kafka-0:9092,kafka-1:9092,kafka-2:9092,kafka-3:9092,kafka-4:9092 
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
      - kafka-3
      - kafka-4

# volumes:
  # zookeeper_data:
    # driver: local
  # kafka_0_data:
    # driver: local
  # kafka_1_data:
    # driver: local
  # kafka_2_data:
    # driver: local
