version: '3.1'
services:
  sqlserver:
    image: microsoft/mssql-server-linux
    container_name: sqlserver
    ports:
      - 1433:1433
    #volumes:
      #- ./data/mssql:/var/opt/mssql
      #- /etc/localtime:/etc/localtime
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ROot^123