version: '3.1'

services:
  mysql: 
    image: mysql:8.0
    container_name: xxljob-db 
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=xxl_job"
    volumes:
      - ./sql-2.3.1:/docker-entrypoint-initdb.d
    #ports:
      #- "3306:3306"
    networks:
      - xxl_job_net
      
  xxljob:
    image: xuxueli/xxl-job-admin:2.3.1
    container_name: xxljob
    ports:
      - "9100:8080"
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root  --spring.datasource.password=123456'
    networks:
      - xxl_job_net
    depends_on:
      - mysql
      
  executor:
    image: xxl-job-executor:2.3.1
    container_name: xxljob-executor
    ports:
      - "9999:9999"
    environment:
      PARAMS: '--xxl.job.admin.addresses=http://xxljob:8080/xxl-job-admin --xxl.job.executor.appname=xxl-job-executor'
    networks:
      - xxl_job_net
    depends_on:
      - xxljob
      
networks:
  xxl_job_net:
    driver: bridge