version: '3.1'
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:v11.1.0
    restart: always  
    container_name: gitlab-runner 
    privileged: true  # 以管理员的身份进行
    volumes:
      - /usr/local/docker/runner/config:/etc/gitlab-runner  # gitlba-runner的配置
      - /var/run/docker.sock:/var/run/docker.sock  # 挂载的是容器中的docker跟宿主机docker的配置 ,目的是让容器中也可以操作宿主机中的docker
